#!/bin/bash
# install-brain.sh: install or upgrade the second brain. Safe to re-run.
#
#   install-brain.sh               install or upgrade
#   install-brain.sh --uninstall   remove hooks, skill and launchd job; keep ~/brain
#
# Never overwrites tasks, decisions, follow-ups, inbox, sessions.log or config
# values. Backs up ~/.claude/settings.json and the skill before changing them.
# Works with macOS bash 3.2 and BSD tools. GENERATED by build.sh; edit src/.
set -eu

BRAIN="$HOME/brain"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
SKILL_DIR="$CLAUDE_DIR/skills/brain"
LABEL="com.brain.tick"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
STAMP="$(date +%Y%m%d-%H%M%S)"
OS="$(uname -s)"

say() { printf '%s\n' "$*"; }
die() { printf 'install-brain: %s\n' "$*" >&2; exit 1; }

PY="$(command -v python3 || true)"
[ -n "$PY" ] || die "python3 is required (macOS: xcode-select --install)"
"$PY" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)' \
  || die "python3 3.6 or newer is required"
command -v git >/dev/null 2>&1 || die "git is required"

# ---------------------------------------------------------------- uninstall
if [ "${1:-}" = "--uninstall" ]; then
  if [ -x "$BRAIN/bin/brain" ]; then
    "$BRAIN/bin/brain" _settings remove
  else
    say "settings: $BRAIN/bin/brain missing; remove the hooks by hand (see README)"
  fi
  if [ -d "$SKILL_DIR" ]; then
    rm -r "$SKILL_DIR" && say "skill: removed $SKILL_DIR"
  fi
  if [ "$OS" = "Darwin" ] && [ -f "$PLIST" ]; then
    launchctl bootout "gui/$(id -u)" "$PLIST" 2>/dev/null \
      || launchctl unload "$PLIST" 2>/dev/null || true
    rm -f "$PLIST" && say "launchd: removed $PLIST"
  fi
  say "Uninstalled. $BRAIN was left intact."
  exit 0
fi
[ "$#" -eq 0 ] || die "unknown option: $1 (use --uninstall or no options)"

# ---------------------------------------------------------------- helpers
# put_file DEST MODE: read content from stdin; replace DEST only if it differs.
put_file() {
  dest="$1"; mode="$2"; tmp="$dest.new.$$"
  cat > "$tmp"
  if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$dest"; say "wrote $dest"
  fi
  chmod "$mode" "$dest"
}
# keep_file DEST: create from stdin only if DEST does not exist (owner data).
keep_file() {
  dest="$1"
  if [ -e "$dest" ]; then cat >/dev/null; else cat > "$dest"; say "created $dest"; fi
}

# ---------------------------------------------------------------- store
mkdir -p "$BRAIN/tasks" "$BRAIN/archive" "$BRAIN/bin/web" "$BRAIN/.state"

@@PUT bin/brain.py 755@@
@@PUT bin/brain_web.py 644@@
@@PUT bin/web/index.html 644@@
@@PUT bin/web/app.css 644@@
@@PUT bin/web/app.js 644@@
@@PUT bin/brain 755@@
@@PUT bin/session-start.sh 755@@
@@PUT bin/session-end.sh 755@@
@@PUT bin/agent-prompt.md 644@@
@@PUT README.md 644@@
@@KEEP tasks/_template.md@@
@@PUT .state/gitignore.default=gitignore 644@@
# .gitignore: add any missing default lines, keep the owner's own lines.
touch "$BRAIN/.gitignore"
while IFS= read -r line; do
  grep -qxF "$line" "$BRAIN/.gitignore" || { printf '%s\n' "$line" >> "$BRAIN/.gitignore"; say "gitignore: added $line"; }
done < "$BRAIN/.state/gitignore.default"

keep_file "$BRAIN/decisions.md" <<'__BRAIN_EOF__'
# Decisions

Big decisions only, newest first. Format:
`## YYYY-MM-DD | task-slug | short title` then Decision / Why / Rejected lines.
__BRAIN_EOF__
keep_file "$BRAIN/followups.md" <<'__BRAIN_EOF__'
# Follow-ups

__BRAIN_EOF__
keep_file "$BRAIN/inbox.md" <<'__BRAIN_EOF__'
# Inbox

__BRAIN_EOF__
[ -e "$BRAIN/sessions.log" ] || { : > "$BRAIN/sessions.log"; say "created $BRAIN/sessions.log"; }

"$BRAIN/bin/brain" _config
"$BRAIN/bin/brain" _migrate

# Keep a copy of this installer so `~/brain/bin/install-brain.sh --uninstall` always works.
if [ -f "$0" ] && [ "$(cd "$(dirname "$0")" && pwd)/$(basename "$0")" != "$BRAIN/bin/install-brain.sh" ]; then
  put_file "$BRAIN/bin/install-brain.sh" 755 < "$0"
fi

# ---------------------------------------------------------------- skill
mkdir -p "$SKILL_DIR"
SKILL_NEW="$SKILL_DIR/.incoming.$$"
cat > "$SKILL_NEW" <<'__BRAIN_EOF__'
@@RAW skill/SKILL.md@@
__BRAIN_EOF__
if [ -f "$SKILL_DIR/SKILL.md" ] && ! cmp -s "$SKILL_NEW" "$SKILL_DIR/SKILL.md"; then
  cp "$SKILL_DIR/SKILL.md" "$SKILL_DIR/SKILL.md.bak-$STAMP"
  say "skill: previous version backed up to SKILL.md.bak-$STAMP"
fi
put_file "$SKILL_DIR/SKILL.md" 644 < "$SKILL_NEW"
rm -f "$SKILL_NEW"

# ---------------------------------------------------------------- hooks
mkdir -p "$CLAUDE_DIR"
"$BRAIN/bin/brain" _settings install

# ---------------------------------------------------------------- git
cd "$BRAIN"
if [ ! -d .git ]; then
  git init -q && say "git: initialised $BRAIN"
fi
if [ -z "$(git config user.email || true)" ]; then
  git config user.email "brain@localhost"
  git config user.name "brain"
fi
git add -A
if ! git diff --cached --quiet 2>/dev/null; then
  git commit -q -m "brain: install/upgrade $STAMP" && say "git: committed"
fi

# ---------------------------------------------------------------- launchd
TICK_MINUTES="$(sed -n 's/^TICK_MINUTES=\([0-9][0-9]*\).*/\1/p' "$BRAIN/config" | tail -n 1)"
TICK_MINUTES="${TICK_MINUTES:-15}"
if [ "$OS" = "Darwin" ]; then
  mkdir -p "$HOME/Library/LaunchAgents"
  # launchd starts jobs with a minimal PATH: record the installer's PATH.
  "$PY" - "$PLIST.gen.$$" "$LABEL" "$BRAIN" "$TICK_MINUTES" <<'__BRAIN_EOF__'
import os, plistlib, sys
out, label, brain, minutes = sys.argv[1:5]
d = {"Label": label,
     "ProgramArguments": [os.path.join(brain, "bin", "brain"), "tick"],
     "StartInterval": int(minutes) * 60, "RunAtLoad": False,
     "WorkingDirectory": brain,
     "EnvironmentVariables": {"PATH": os.environ.get("PATH", "/usr/bin:/bin"),
                              "HOME": os.environ["HOME"]},
     "StandardOutPath": os.path.join(brain, ".state", "launchd.log"),
     "StandardErrorPath": os.path.join(brain, ".state", "launchd.log"),
     "ProcessType": "Background"}
with open(out, "wb") as f:
    plistlib.dump(d, f)
__BRAIN_EOF__
  put_file "$PLIST" 644 < "$PLIST.gen.$$"
  rm -f "$PLIST.gen.$$"
  launchctl bootout "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl unload "$PLIST" 2>/dev/null || true
  if launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null || launchctl load -w "$PLIST" 2>/dev/null; then
    say "launchd: $LABEL loaded (every $TICK_MINUTES min)"
  else
    say "launchd: could not load $PLIST; run: launchctl bootstrap gui/\$(id -u) $PLIST"
  fi
else
  say "launchd: not macOS, skipped. To tick on this system, add to crontab:"
  say "  */$TICK_MINUTES * * * * $BRAIN/bin/brain tick >> $BRAIN/.state/cron.log 2>&1"
fi

# ---------------------------------------------------------------- done
CLAUDE_FOUND="$(sed -n 's/^CLAUDE_BIN=//p' "$BRAIN/config" | tail -n 1)"
[ -n "$CLAUDE_FOUND" ] || say "warning: claude CLI not found; set CLAUDE_BIN in $BRAIN/config so the tick can run the brain agent"
say ""
say "Brain installed at $BRAIN. Start a new Claude Code session to use it."
if ! git -C "$BRAIN" remote get-url origin >/dev/null 2>&1; then
  say "Optional backup to a private GitHub repo (run once):"
  say "  cd $BRAIN && gh repo create brain --private --source . --push"
fi
say "Uninstall: $BRAIN/bin/install-brain.sh --uninstall   (keeps $BRAIN)"
